Check for CRSF Token in the Header first
mzur/kirby-form pull request #11
Opened 2022-02-19 11:21 UTC by marcus-at-localhost

Since the CRSF Token can be delivered via http header or get param (https://getkirby.com/docs/reference/objects/http/request/csrf) this should be taken into account while validating. This might solve some problems with handling upload forms with ajax as well.

2022-02-19 12:51 UTC, mzur requested changes
Thanks! Could you please add a test similar to [`testValidateCsrfSuccess`](https://github.com/mzur/kirby-form/blob/3ba0f51769fd878fcd7d1e01359bb6880e0343bc/tests/FormTest.php#L214-L219) for this case (using the `$_SERVER` array)?

2022-02-20 20:36 UTC, marcus-at-localhost commented
Apologies, this is a field I have no expertise in (yet).  :/

2022-02-21 08:00 UTC, mzur commented
Ok no problem but then this has to wait a while until I get around to do it myself.

2022-02-21 22:34 UTC, marcus-at-localhost commented
Thank you!

2022-02-22 21:12 UTC, merged

2022-02-23 09:44 UTC, marcus-at-localhost commented
@mzur thanks for writing the test and verifying!